<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- This document was generated by the SagaDB build mechanism on %%datecreated%% -->
<html>
<body>
<h2>Citing this saga</h2> 

<p>Anonymous, "%%title%%", %%trans%%, <em>Icelandic Saga Database</em>, Sveinbjorn Thordarson (ed.), URL = &lt;http://www.sagadb.org/%%basename%%&gt;</p>        

<a name="about"></a> 
<h2>About this saga</h2> 

<table border="1" cellpadding="4"> 
<tr> 
   <td><p align="right">Title:</p></td> 
   <td><strong>%%title%%</strong></td> 
</tr> 
<tr> 
   <td><p align="right">Language:</p></td> 
   <td><strong>%%language%%</strong></td> 
</tr> 
<tr> 
   <td><p align="right">Date added:</p></td> 
   <td><strong>%%date_added%%</strong></td> 
</tr> 
       <tr> 
   <td><p align="right">Translator:</p></td> 
   <td><strong>%%trans%%</strong></td> 
</tr> 
<tr> 
   <td><p align="right">Translation date:</p></td> 
   <td><strong>%%trans_date%%</strong></td> 
</tr> 
<tr> 
   <td><p align="right">Title of original:</p></td> 
   <td><strong>%%title_orig%%</strong></td> 
</tr> 

</table> 
<p>%%orig_publication%%</p> 

<h2>Source</h2> 

<ul><li><a href="%%sourceurl%%">%%sourcename%%</a></li></ul>

</body>
</html>