<!doctype html>
<!-- This document was generated by the SagaDB build mechanism on %%datecreated%% -->
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Language" content="en,is">
    <meta http-equiv="Content-Disposition" content="inline; filename=[PAGENAME].html">
    
    <title>%%title%% - Icelandic Saga Database</title>
    
    <link rel="stylesheet" type="text/css" href="/files/style.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i">
    <link rel="icon" type="image/vnd.microsoft.icon" href="/images/favicon.ico">
    
    <meta name="robots" content="index, follow, imageindex, archive">
    <meta name="googlebot" content="index, follow, imageindex, archive">
    <meta name="domain" content="sagadb.org">
    <meta name="location" content="Reykjavik, Iceland">
    <meta name="operator" content="Sveinbjörn Þórðarson">
    <meta name="geo.position" content="64;-22">
    <meta name="geo.region" content="IS-1">
    <meta name="geo.placename" content="Reykjavík">
    
    <!-- OpenGraph metadata -->
    <meta property="og:title" content="%%title%% - Icelandic Saga Database">
    <meta property="og:site_name" content="Icelandic Saga Database"> 
    <meta property="og:type" content="article">
    <meta property="og:image" content="http://dev.sagadb.org/images/egill-og.jpg">    
    
  </head>
  <body>
      
      <div class="nav">
          <ul class="dropdown menu">
            <li class="homelink"><a href="/">⚔</a></li>
            <li class="homeurl"><a href="/"><strong>sagadb.org</strong></a></li>
            <li><a href="index_az">Index</a></li>
            <li><a href="downloads">Downloads</a></li>
            <li><a href="about">About</a></li>
          </ul>
      </div>    
            
    <div class="content row">
        <div class="small-12 medium-9 medium-centered columns">
        <!-- CONTENT BEGINS -->    
    
    
    %%content%%
    
    
    
        <!-- CONTENT ENDS -->
        </div>
    </div>

    <footer>
        The Icelandic Saga Database is maintained by
        <a href="mailto:sveinbjornt@gmail.com">Sveinbjörn Þórðarson</a>. 
    </footer>

    </body>
</html>
